# Generated by Django 5.1 on 2024-08-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='rsvp_status',
        ),
    ]
