# Generated by Django 5.0.7 on 2024-08-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('Alumni_ID', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone_Number', models.CharField(blank=True, max_length=15, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('Graduation_Year', models.IntegerField()),
                ('Degree', models.CharField(max_length=100)),
                ('Major', models.CharField(max_length=100)),
                ('Occupation', models.CharField(max_length=100)),
                ('Company', models.CharField(blank=True, max_length=100, null=True)),
                ('LinkedIn_Profile', models.URLField(blank=True, null=True)),
                ('Profile_Picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('Bio', models.TextField(blank=True, null=True)),
                ('notification_preferences', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
