# Generated by Django 5.1 on 2024-08-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='alumni',
            old_name='Alumni_ID',
            new_name='alumni_ID',
        ),
        migrations.RenameField(
            model_name='alumni',
            old_name='Bio',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='alumni',
            old_name='Company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='alumni',
            old_name='Degree',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='alumni',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='alumni',
            old_name='First_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='alumni',
            old_name='Graduation_Year',
            new_name='graduation_year',
        ),
        migrations.RenameField(
            model_name='alumni',
            old_name='Last_Name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='alumni',
            old_name='LinkedIn_Profile',
            new_name='linkedIn_profile',
        ),
        migrations.RenameField(
            model_name='alumni',
            old_name='Major',
            new_name='major',
        ),
        migrations.RenameField(
            model_name='alumni',
            old_name='Occupation',
            new_name='occupation',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='Phone_Number',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='Profile_Picture',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='notification_preferences',
        ),
        migrations.AddField(
            model_name='alumni',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
    ]
