# Generated by Django 5.1 on 2024-08-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0005_alter_alumni_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='phone_number',
            field=models.IntegerField(max_length=13, unique=True),
        ),
    ]
