# Generated by Django 5.1 on 2024-08-24 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MessageLog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ml',
            old_name='first_name',
            new_name='phone_number',
        ),
    ]
