# Generated by Django 5.1 on 2024-08-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageLog', '0002_rename_first_name_ml_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ml',
            old_name='phone_number',
            new_name='p_no',
        ),
        migrations.AddField(
            model_name='ml',
            name='message',
            field=models.TextField(default='No text'),
            preserve_default=False,
        ),
    ]
