# Generated by Django 5.1 on 2024-08-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('Normal', 'normal'), ('Critical', 'critical')], max_length=10),
        ),
    ]
